repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.55.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      args:
        - --args=-json
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=./TFDOC.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-exiting-file=true      # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
    - id: terraform_tflint
      args:
      - --args=--enable-rule=terraform_documented_variables
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: check-json
    - id: check-yaml
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.24.0
  hooks:
  - id: markdownlint

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false