repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.55.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      args:
        - --args=-json
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=./TFDOC.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-exiting-file=true      # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
    - id: terraform_tflint
      args:
      - --args=--enable-rule=terraform_documented_variables
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: mixed-line-ending
      args: ['--fix=lf']