on:
  push:
    branches:
    - main
    paths:
    - 'bicep/*'
  pull_request:
    paths:
    - 'bicep/*'
  workflow_dispatch:

name: 'Bicep'

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: pwsh

env:
  workingDir: 'bicep'

jobs:
  bicep:
    name: 'Bicep'
    runs-on: ubuntu-latest
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AAD_APP_ID }}
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    
    - name: 'Az CLI list resource groups'
      working-directory: 'bicep'
      run: az group list -o table
    
    - name: 'Az CLI upgrade bicep'
      working-directory: 'bicep'
      run: az bicep upgrade
    
    - name: 'Az CLI build/validate bicep file'
      working-directory: 'bicep'
      run: az bicep build --file 'main.bicep'

    - name: 'Az CLI what-if bicep deployment'
      if: github.event_name == 'pull_request'
      working-directory: 'bicep'
      run: az deployment sub what-if --location westeurope --template-file main.bicep
    
    - name: 'Az CLI create bicep deployment'
      working-directory: 'bicep'
      if: github.ref == 'refs/heads/main'
      run: az deployment sub create --name 'bicep-deployment' --location 'westeurope' --template-file main.bicep