on:
  push:
    paths:
    - 'terraform/*'
  pull_request:
    paths:
    - 'terraform/*'
  workflow_dispatch:

name: 'Terraform'

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: pwsh
    working-directory: 'terraform'

jobs:
  terraform_plan:
    name: 'Terraform'
    environment: 'test'
    runs-on: ubuntu-latest
    if: github.ref  != 'refs/heads/main'
    env:
      ARM_CLIENT_ID: ${{ secrets.AAD_APP_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AAD_APP_ID }}
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Init
      run: terraform init -backend-config "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -backend-config "tenant_id=${{ secrets.AAD_TENANT_ID }}" -backend-config "client_id=${{ secrets.AAD_APP_ID }}"
    
    - name: Terraform Plan and validate
      run: |
        terraform plan -out tfplan
  terraform_apply:
    name: 'Terraform'
    environment: 'production'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      ARM_CLIENT_ID: ${{ secrets.AAD_APP_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AAD_APP_ID }}
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init -backend-config "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -backend-config "tenant_id=${{ secrets.AAD_TENANT_ID }}" -backend-config "client_id=${{ secrets.AAD_APP_ID }}"

    - name: Terraform Apply
      run: terraform apply --auto-approve
