on:
  push:
    branches:
    - main
    paths:
    - 'terraform/*'
  pull_request:
    paths:
    - 'terraform/*'

name: 'Terraform'

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AAD_APP_ID }}
        tenant-id: ${{ secrets.AAD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: 'Run az commands'
      run: |
        az account show
        az group list -o table
      
 
    # - name: 'Terraform Format'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_subcommand: 'fmt'
    #     tf_actions_working_dir: "./terraform"
         
    # - name: 'Terraform Init'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_subcommand: 'init'
    #     tf_actions_working_dir: "./terraform"
 
    # - name: 'Terraform Validate'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_subcommand: 'validate'
    #     tf_actions_working_dir: "./terraform"
         
    # - name: 'Terraform Plan'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_subcommand: 'plan'
    #     tf_actions_working_dir: "./terraform"
 
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.14.8
    #     tf_actions_subcommand: 'apply'
    #     tf_actions_working_dir: "./terraform"